-- 최솟값 구하기
SELECT MIN(DATETIME) AS '시간'
FROM ANIMAL_INS;

-- 동물 수 구하기
SELECT COUNT(ANIMAL_ID) AS count
FROM ANIMAL_INS;

-- 중복 제거하기
SELECT COUNT(DISTINCT(NAME)) AS 'COUNT'
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

-- 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY NAME;